In [3]:
import torch

In [20]:
x=torch.ones(2,2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [21]:
y=x+2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [22]:
print(y.grad_fn)

In [8]:
#tensor and Function are interconnected and build up an acyclic graph, that encodes a complete history of computation.
#Each tensor has a .grad_fn attribute that references a Function that has created the Tensor 
#(except for Tensors created by the user - their grad_fn is None).



In [23]:
z=y*7*3
out=z.mean()
print(x,out)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True) tensor(63., grad_fn=<MeanBackward1>)


In [24]:
#requires_grad: default:False

a=torch.randn(2,2)
a=((a*3)/(a-1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b=(a*a).sum()
print(b.grad_fn)

False
True


In [25]:
print(a.grad_fn)

None


In [26]:
out.backward() #out contains a single scalar.,(=out.backward(torch.tensor(1.)))

In [27]:
print(x.grad)

tensor([[5.2500, 5.2500],
        [5.2500, 5.2500]])


In [31]:
x=torch.randn(3, requires_grad=True)
y=x*2
print(y)
#print(y.data.norm())#torch.sqrt(torch.sum(torch.pow(y,2))
while y.data.norm()<1000:
    y=y*2
print(y)

tensor([ 1.5040, -2.9973,  2.3511], grad_fn=<MulBackward0>)
tensor([ 385.0221, -767.3088,  601.8819], grad_fn=<MulBackward0>)


In [32]:
v=torch.tensor([0.1,1.0,0.0001],dtype=torch.float)
y.backward(v)

print(x.grad)

tensor([5.1200e+01, 5.1200e+02, 5.1200e-02])


In [33]:
#You can also stop autograd from tracking history on Tensors with .requires_grad=True by wrapping the code block in with torch.no_grad():

print(x.requires_grad)
print((x**2).requires_grad)

with torch.no_grad():
    print((x**2).requires_grad)

True
True
False
